parameters:
#    projet_general.example.class: Projet\GeneralBundle\Example

services:
#    projet_general.example:
#        class: %projet_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
